---
kind: Namespace
apiVersion: v1
metadata:
  name: es
  labels:
    name: es
    
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cerebro
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cerebro-gui
  namespace: es
data:
  SPECIAL_LEVEL: very
  SPECIAL_TYPE: charm

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cerebro
  name: cerebro-gui-test
  namespace: es
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: cerebro
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cerebro
    spec:
      volumes:
        - name: pv-cerebro
          persistentVolumeClaim:
            claimName: config
      containers:
      - args:
        image: lmenezes/cerebro:0.9.4
        imagePullPolicy: Always
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: cerebro
        ports:
        - containerPort: 9000
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: http
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/db/cerebro
          name: db
        - mountPath: /etc/cerebro
          name: config
        - mountPath: /opt/cerebro/logs/
          name: logs
        - mountPath: /tmp
          name: tmp
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      volumes:
      - emptyDir: {}
        name: db
      - configMap:
          defaultMode: 420
          name: cerebro-gui
        name: config
      - emptyDir: {}
        name: logs
      - emptyDir: {}
        name: tmp

---
apiVersion: v1
kind: Service
metadata:
  name: cerebro-svc
  namespace: es
spec:
  selector:
    app: cerebro
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000